language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
  - "6" # per https://github.com/activescott/serverless-http-invoker/issues/5
  #- "9" # oddly new versions of mocha don't work on node 9, but do work on 6, 8, & 10+: https://travis-ci.org/activescott/serverless-http-invoker/jobs/554058213#L463
cache: yarn
